set number
set hlsearch
set ignorecase
set showmatch
set softtabstop=4
set shiftwidth=4
set expandtab
set laststatus=2

set statusline+=%#PmenuSel#
set statusline+=\ %F\ line\ %l\ col\ %c\ pos\ %p

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

set tags=~/.ctags
nnoremap <F3> :!/bin/bash ~/.update_ctags.sh <CR><CR> :echo "CTags updated!" <CR>
